# -*- mode: ruby -*-
# vim: set ft=ruby :
# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:inetRouter => {
        :box_name => "centos/6",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                   {ip: '192.168.240.1', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1router-net"},
                   {ip: '192.168.250.1', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2router-net"},
                   {adapter: 8, auto_config: false, virtualbox__intnet: true},
                ]
  },
  
 :centralServer => {
       :box_name => "centos/7",
       :net => [
                  {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: true},
                  {adapter: 4, auto_config: false, virtualbox__intnet: true},
               ]
 },
  :office1Router => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.240.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office1router-net"},
                   {ip: '192.168.2.1', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "office1-dev"},
                   {ip: '192.168.2.65', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office1-test-server"},
                   {ip: '192.168.2.129', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office1-managers"},
                   {ip: '192.168.2.193', adapter: 6, netmask: "255.255.255.192", virtualbox__intnet: "office1-hw"},
                ]
  },
  :office1Server => {
       :box_name => "centos/7",
       :net => [
                  {ip: '192.168.2.194', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-hw"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: true},
                  {adapter: 4, auto_config: false, virtualbox__intnet: true},
               ]
 },
 # :office2Router => {
 #       :box_name => "centos/7",
 #       :net => [
 #                  {ip: '192.168.250.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "office2router-net"},
 #                  {ip: '192.168.1.1', adapter: 3, netmask: "255.255.255.128", virtualbox__intnet: "office2-dev"},
 #                  {ip: '192.168.1.129', adapter: 4, netmask: "255.255.255.192", virtualbox__intnet: "office2-test"},
 #                  {ip: '192.168.1.193', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "office2-hw"},
 #               ]
 # },
 #    :office2Server => {
 #       :box_name => "centos/7",
 #      :net => [
 #                  {ip: '192.168.1.194', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office2-hw"},
 #                  {adapter: 3, auto_config: false, virtualbox__intnet: true},
 #                  {adapter: 4, auto_config: false, virtualbox__intnet: true},
 #               ]
 # },
#   :testClient1 => {
#     :box_name => "centos/7",
#     :net => [
#                {ip: '192.168.2.66', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-test-server"},
#                {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLan"},
               
#             ]
# },
#   :testClient2 => {
#   :box_name => "centos/7",
#   :net => [
#              {ip: '192.168.2.67', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-test-server"},
#              {ip: '10.10.10.254', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLan"},

#           ]
# },
#   :testServer1 => {
#   :box_name => "centos/7",
#   :net => [
#              {ip: '192.168.2.68', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-test-server"},
#              {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLan"},
             
#           ]
# },
#   :testServer2 => {
#   :box_name => "centos/7",
#   :net => [
#              {ip: '192.168.2.69', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "office1-test-server"},
#              {ip: '10.10.10.1', adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "testLan"},
#           ]
# },
  
}

Vagrant.configure("2") do |config|
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 256
        v.cpus = 1
      end

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.ip_forward=1
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            ip route add 192.168.0.0/16 via 192.168.255.2
            SHELL
            #box.vm.provision "shell", path: "../lesson_2/bond_settings.sh", :args => "inetRouter"
        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            sysctl net.ipv4.ip_forward=1
            ip route add 192.168.1.0/24 via 192.168.250.2
            ip route add 192.168.2.0/24 via 192.168.240.2
            SHELL
            #box.vm.provision "shell", path: "../lesson_2/bond_settings.sh", :args => "centralRouter"
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            SHELL
        when "office1Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.2.193" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            SHELL
        when "office2Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.1.193" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            SHELL
        when "office1Router"
            
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.240.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            sysctl net.ipv4.ip_forward=1
            SHELL
        when "office2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.250.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            sysctl net.ipv4.ip_forward=1
            SHELL
        when "testClient1"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
            box.vm.provision "shell", path: "../lesson_2/vlan_settings.sh", :args => "testClient1"
        when "testClient2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              SHELL
            box.vm.provision "shell", path: "../lesson_2/vlan_settings.sh", :args => "testClient2"
        when "testServer1"
              box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              # sed -c -i "s/#PubkeyAuthentication yes/PubkeyAuthentication yes/" /etc/ssh/sshd_config
              # systemctl restart sshd
              SHELL
              box.vm.provision "shell", path: "../lesson_2/vlan_settings.sh", :args => "testServer1"
        when "testServer2"
              box.vm.provision "shell", run: "always", inline: <<-SHELL
              echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
              echo "GATEWAY=192.168.2.65" >> /etc/sysconfig/network-scripts/ifcfg-eth1
              systemctl restart network
              # sed -c -i "s/#PubkeyAuthentication yes/PubkeyAuthentication yes/" /etc/ssh/sshd_config
              # systemctl restart sshd
              SHELL
              box.vm.provision "shell", path: "../lesson_2/vlan_settings.sh", :args => "testServer2"
        end

      end

  end
  
  
end
