MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
                   {adapter: 3, auto_config: false, virtualbox__intnet: true},
                ]
  },
  :inetRouter2 => {
    :box_name => "centos/7",
    :public => { :adapter => 2, :bridge => "enp1s0" },
    :net => [
               {ip: '192.168.255.3', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
            ]
},
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                   {ip: '192.168.0.33', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "hw-net"},
                   {ip: '192.168.0.65', adapter: 5, netmask: "255.255.255.192", virtualbox__intnet: "mgt-net"},
                   {ip: '192.168.240.1', adapter: 6, netmask: "255.255.255.252", virtualbox__intnet: "office1router-net"},
                   {ip: '192.168.250.1', adapter: 7, netmask: "255.255.255.252", virtualbox__intnet: "office2router-net"},
                   {adapter: 8, auto_config: false, virtualbox__intnet: true},
                ]
  },
  
 :centralServer => {
       :box_name => "centos/7",
       :net => [
                  {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                  {adapter: 3, auto_config: false, virtualbox__intnet: true},
                  {adapter: 4, auto_config: false, virtualbox__intnet: true},
               ]
 },
  
}

Vagrant.configure("2") do |config|
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 256
        v.cpus = 1
      end
    
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "provision/main.yml"
      end

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
#        when "inetRouter"
#          box.vm.provision "shell", run: "always", inline: <<-SHELL
            #sysctl net.ipv4.conf.all.forwarding=1
            #iptables-restore < /vagrant/iptables
            #iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
            #ip route add 192.168.0.0/16 via 192.168.255.2
            #ip route add 192.168.1.0/28 via 192.168.255.2
            #sed -i '66s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            #service sshd restart
            #setenforce 0
#            SHELL
        when "inetRouter2"
            box.vm.provision "shell", run: "always", inline: <<-SHELL
 #            echo net.ipv4.conf.all.forwarding=1 >> /etc/sysctl.conf
 #            echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf
 #            sysctl -p /etc/sysctl.conf
             echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
             echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1 
             echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth2
#             systemctl restart network
#             ip route add 192.168.0.0/16 via 192.168.255.2
#             chmod +x /vagrant/iptables-nat.sh
             #bash /vagrant/iptables-nat.sh

              SHELL

        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            #echo net.ipv4.ip_forward = 1 >> /etc/sysctl.conf
            #sysctl -p /etc/sysctl.conf
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.255.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
            #ip route add 192.168.1.0/24 via 192.168.250.2
            #ip route add 192.168.2.0/24 via 192.168.240.2
            #chmod +x /vagrant/knock.sh
            #setenforce 0
            #sudo yum install nmap -y
            #systemctl stop firewalld
            SHELL

        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
    #        yum install epel-release -y
    #        yum install nginx -y
    #        systemctl start nginx
    #        systemctl stop firewalld
    #        setenforce 0
            SHELL
         end

      end

  end

  
  
end
