- hosts: centralServer
  become: True
  vars_files:
    - vars/main.yml
  tasks:
    - name: write template to /etc/hosts
      template:
        src: hosts.j2
        dest: /etc/hosts
    - name: write template to /etc/resolv.conf
      template:
        src: resolv_server.j2
        dest: /etc/resolv.conf

    - name: Ensure software is installed (yum)
      yum: name={{ item }} state=present
      with_items: "{{ ipaserver_packages }}"
      when: ansible_distribution == "CentOS" or
        (ansible_distribution == "Fedora" and ansible_distribution_version|int <= 21)

    - name: Install IPA server
      raw: "{{ ipaserver_base_command }} --realm {{ ipaserver_realm }} --domain {{ ipaserver_domain }}
        -a {{ ipaserver_admin_password }}
        -p {{ ipaserver_dir_admin_password }}
        --hostname={{ ipaserver_hostname }}
        --ip-address={{ ipaserver_ip }}
        {{ '--forwarder=%s' % ipaserver_dns_forwarder
          if ipaserver_dns_forwarder | default(False) else '--no-forwarders' }}
        {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
        {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }}
          creates=/etc/ipa/default.conf"

- hosts: clients
  become: True
  vars_files:
    - vars/main.yml
  tasks:
    - name: Instal client packages
      yum: name={{ item }} state=present
      with_items: "{{ ipaclient_packages }}"

    - name: write template to /etc/resolv.conf
      template:
        src: resolv_client.j2
        dest: /etc/resolv.conf

    - name: Install ipa-client
      raw: "{{ ipaclient_base_command }}
        --force-join
        --force-ntpd
        --realm {{ipaserver_realm}}
        --domain {{ ipaserver_domain }}
        --principal {{ ipaserver_admin_username }}@{{ ipaserver_realm }}
        --password {{ ipaserver_admin_password }}
        --hostname={{ ansible_fqdn }}
        {{ '--mkhomedir' if ipaclient_mkhomedir | default(True) else '' }}
        {{ '--ssh-trust-dns' if ipaclient_ssh_trust_dns | default(False) else '' }}
        {{ '' if ipaclient_setup_ntp | default(True) else '--no-ntp' }}
        {{ '' if ipaclient_configure_ssh | default(True) else '--no-ssh' }}
        {{ '' if ipaclient_configure_sshd | default(True) else '--no-sshd' }}
        creates=/etc/ipa/default.conf"